In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 데이터 로드 및 조건 필터링
파일 크기가 클 수 있으므로 `chunksize`를 사용하여 10만 행씩 나누어 읽어옵니다. 각 chunk에서 조건에 맞는 데이터만 필터링하여 리스트에 모은 후, 마지막에 하나의 데이터프레임으로 합칩니다.

(No.23) C1L120004 최초신용카드개설일자로부터경과일수(활성카드)(미해지)

= 최근12개월동안 이용내역이 있는 신용카드 +체크카드(전체) 중최초로 등록된 신용카드(신용카드/신용카드+체크카드) 개설정보의 최초개설일자로부터 기준일자까지의 기간

(No.48) 최초대출개설일자로부터의경과일수(해지포함)

= KCB에 등록된 대출개설정보 중 최초 개설된 개인대출정보의 대출개설일자로부터 기준일자까지의 기간(해지포함)

(No.111) 연체건수(해제포함)

= 연체정보(미해제+해제)의 총건수

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/data/개인CB_씬파일러.csv'
chunk_size = 100000  # 메모리 상황에 따라 조절 가능

filtered_chunks = []

# 파일을 chunk 단위로 읽어오기
for chunk in pd.read_csv(file_path, chunksize=chunk_size):
    # 조건 필터링: D10110000, C1L120004, L10173000이 모두 0이고 AGE_BAND가 2
    condition = (
        (chunk['D10110000'] == 0) &
        (chunk['C1L120004'] == 0) &
        (chunk['L10173000'] == 0) &
        (chunk['AGE_BAND'] == 2)
    )

    # 조건에 맞는 데이터만 리스트에 추가
    filtered_chunks.append(chunk[condition])

# 필터링된 모든 chunk를 하나의 데이터프레임으로 병합
df_filtered = pd.concat(filtered_chunks, ignore_index=True)

print(f"필터링된 총 데이터 수: {len(df_filtered):,}개")
display(df_filtered.head())

필터링된 총 데이터 수: 624,865개

,STDT,ID,GENDER,AGE_BAND,C1Z001373,C1M2B4W03,C1M2B5W03,C1Z001386,C1M210000,C1M210001,...,AP0910001,AP0910002,AS120G001,SCORE,SCORE_6M,PERF1,PERF2,PERF3,PERF4,기준년월
0,201912,2030E3D1E65F5466C39FC92E8F11BA7CC3A07903284F6B...,1,2,-692,0,0,-14451,0,0,...,9,9,2,759,751,0,0,0,0,201912
1,201912,17E62506183301DE713B1F1C6A3322E7C4511CC35B7333...,2,2,1425,0,0,-650,0,0,...,9,9,1,671,661,0,0,0,0,201912
2,201912,91781E6658AA06B1A6EC71B6F3E415362277070FE14DAC...,2,2,-195,0,0,-9620,0,0,...,9,9,3,750,754,0,0,0,0,201912
3,201912,A2CD0CB6B229D2D3A558881118CD3C6465C1E42F3BF417...,1,2,3182,0,0,8245,0,0,...,9,9,3,730,725,0,0,0,0,201912
4,201912,CAD163B2B602192B94CF153EF974B8DAABC58037CD0EA6...,1,2,-1286,0,0,-12594,0,0,...,9,9,3,754,748,0,0,0,0,201912

### PERF 분포 분석
필터링된 데이터에서 `PERF` 컬럼의 값별 빈도수와 비율을 확인하고, 시각화를 통해 분포를 분석합니다.

In [ ]:
import pandas as pd
from IPython.display import display

# 1. 필터링된 데이터 분포 계산 (AGE_BAND=2 + 추가 3개 컬럼 반영)
perf_columns = [col for col in df_filtered.columns if 'PERF' in col]

summary_data_filtered = []
for col in perf_columns:
    counts = df_filtered[col].value_counts(dropna=False)
    ratios = df_filtered[col].value_counts(normalize=True, dropna=False) * 100
    for val in counts.index:
        summary_data_filtered.append({
            'Column': col,
            'Value': val,
            'Count_Filtered': counts[val],
            'Ratio(%)_Filtered': round(ratios[val], 4)
        })
summary_df_filtered = pd.DataFrame(summary_data_filtered).sort_values(by=['Column', 'Value']).reset_index(drop=True)

# 2. 전체 데이터셋 분포 계산 (기존 씬파일러 정의)
file_path = '/content/drive/MyDrive/data/개인CB_씬파일러.csv'
chunk_size = 100000
total_counts = {col: {} for col in perf_columns}
total_rows = 0

# 메모리와 속도를 위해 PERF 관련 컬럼만 지정하여 읽기
for chunk in pd.read_csv(file_path, chunksize=chunk_size, usecols=perf_columns):
    total_rows += len(chunk)
    for col in perf_columns:
        counts = chunk[col].value_counts(dropna=False)
        for val, count in counts.items():
            total_counts[col][val] = total_counts[col].get(val, 0) + count

summary_data_total = []
for col in perf_columns:
    for val, count in total_counts[col].items():
        ratio = (count / total_rows) * 100 if total_rows > 0 else 0
        summary_data_total.append({
            'Column': col,
            'Value': val,
            'Count_Total': int(count),
            'Ratio(%)_Total': round(ratio, 4)
        })
summary_df_total = pd.DataFrame(summary_data_total).sort_values(by=['Column', 'Value']).reset_index(drop=True)

# 3. 각각 출력
print("--- 기존 씬파일러 정의에서의 PERF 분포 (전체 데이터) ---")
display(summary_df_total)

print("\n--- AGE_BAND=2 + 추가 3개 컬럼 반영 PERF 분포 (필터링 데이터) ---")
display(summary_df_filtered)

--- 기존 씬파일러 정의에서의 PERF 분포 (전체 데이터) ---

  Column  Value  Count_Total  Ratio(%)_Total
0  PERF1      0      3251097         99.9037
1  PERF1      1         3133          0.0963
2  PERF2      0      3249562         99.8566
3  PERF2      1         4668          0.1434
4  PERF3      0      3254155         99.9977
5  PERF3      1           75          0.0023
6  PERF4      0      3251463         99.9150
7  PERF4      1         2767          0.0850

--- AGE_BAND=2 + 추가 3개 컬럼 반영 PERF 분포 (필터링 데이터) ---

  Column  Value  Count_Filtered  Ratio(%)_Filtered
0  PERF1      0          624821            99.9930
1  PERF1      1              44             0.0070
2  PERF2      0          624716            99.9762
3  PERF2      1             149             0.0238
4  PERF3      0          624865           100.0000
5  PERF4      0          624849            99.9974
6  PERF4      1              16             0.0026

In [ ]:
import pandas as pd
from IPython.display import display

# 1. 이미 필터링된 데이터에서 STDT == 202212 인 데이터만 추출
# (STDT가 정수형인지 문자열인지 고려하여 정수형으로 필터링, 안 될 경우를 대비해 int 변환도 가능하지만 통상적으로 정수/문자열 모두 처리되도록 작성)
df_202212 = df_filtered[df_filtered['STDT'].astype(str) == '202212']

# 2. 분포 계산을 위한 PERF 컬럼 확인
perf_columns = [col for col in df_202212.columns if 'PERF' in col]

summary_data_202212 = []
for col in perf_columns:
    counts = df_202212[col].value_counts(dropna=False)
    ratios = df_202212[col].value_counts(normalize=True, dropna=False) * 100
    for val in counts.index:
        summary_data_202212.append({
            'Column': col,
            'Value': val,
            'Count': counts[val],
            'Ratio(%)': round(ratios[val], 4)
        })

# 3. 데이터프레임 생성 및 정렬
summary_df_202212 = pd.DataFrame(summary_data_202212).sort_values(by=['Column', 'Value']).reset_index(drop=True)

# 4. 결과 출력
print(f"--- STDT=202212 조건 추가 반영 PERF 분포 (대상: {len(df_202212):,}건) ---")
display(summary_df_202212)

--- STDT=202212 조건 추가 반영 PERF 분포 (대상: 171,751건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  171751  100.0000
1  PERF2      0  171750   99.9994
2  PERF2      1       1    0.0006
3  PERF3      0  171751  100.0000
4  PERF4      0  171751  100.0000

In [ ]:
import pandas as pd
from IPython.display import display

# 1. 이미 필터링된 데이터에서 STDT == 201912 인 데이터만 추출
df_201912 = df_filtered[df_filtered['STDT'].astype(str) == '201912']

# 2. 분포 계산을 위한 PERF 컬럼 확인
perf_columns = [col for col in df_201912.columns if 'PERF' in col]

summary_data_201912 = []
for col in perf_columns:
    counts = df_201912[col].value_counts(dropna=False)
    ratios = df_201912[col].value_counts(normalize=True, dropna=False) * 100
    for val in counts.index:
        summary_data_201912.append({
            'Column': col,
            'Value': val,
            'Count': counts[val],
            'Ratio(%)': round(ratios[val], 4)
        })

# 3. 데이터프레임 생성 및 정렬
summary_df_201912 = pd.DataFrame(summary_data_201912).sort_values(by=['Column', 'Value']).reset_index(drop=True)

# 4. 결과 출력
print(f"--- STDT=201912 조건 추가 반영 PERF 분포 (대상: {len(df_201912):,}건) ---")
display(summary_df_201912)

--- STDT=201912 조건 추가 반영 PERF 분포 (대상: 113,023건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  112984   99.9655
1  PERF1      1      39    0.0345
2  PERF2      0  112887   99.8797
3  PERF2      1     136    0.1203
4  PERF3      0  113023  100.0000
5  PERF4      0  113011   99.9894
6  PERF4      1      12    0.0106

In [ ]:
import pandas as pd
from IPython.display import display

# 대상 연월 리스트
target_stdt = ['201912', '202012', '202112', '202212']

# 분포 계산을 위한 PERF 컬럼 확인
perf_columns = [col for col in df_filtered.columns if 'PERF' in col]

for stdt in target_stdt:
    # 각 연월별 데이터 추출
    df_temp = df_filtered[df_filtered['STDT'].astype(str) == stdt]

    summary_data = []
    # 각 PERF 컬럼별 분포 계산
    for col in perf_columns:
        counts = df_temp[col].value_counts(dropna=False)
        ratios = df_temp[col].value_counts(normalize=True, dropna=False) * 100
        for val in counts.index:
            summary_data.append({
                'Column': col,
                'Value': val,
                'Count': counts[val],
                'Ratio(%)': round(ratios[val], 4)
            })

    # 데이터프레임 생성 및 정렬
    summary_df = pd.DataFrame(summary_data).sort_values(by=['Column', 'Value']).reset_index(drop=True)

    # 결과 개별 출력
    print(f"\n--- STDT={stdt} 조건 추가 반영 PERF 분포 (대상: {len(df_temp):,}건) ---")
    display(summary_df)

--- STDT=201912 조건 추가 반영 PERF 분포 (대상: 113,023건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  112984   99.9655
1  PERF1      1      39    0.0345
2  PERF2      0  112887   99.8797
3  PERF2      1     136    0.1203
4  PERF3      0  113023  100.0000
5  PERF4      0  113011   99.9894
6  PERF4      1      12    0.0106

--- STDT=202012 조건 추가 반영 PERF 분포 (대상: 195,550건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  195546   99.9980
1  PERF1      1       4    0.0020
2  PERF2      0  195543   99.9964
3  PERF2      1       7    0.0036
4  PERF3      0  195550  100.0000
5  PERF4      0  195547   99.9985
6  PERF4      1       3    0.0015

--- STDT=202112 조건 추가 반영 PERF 분포 (대상: 144,541건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  144540   99.9993
1  PERF1      1       1    0.0007
2  PERF2      0  144536   99.9965
3  PERF2      1       5    0.0035
4  PERF3      0  144541  100.0000
5  PERF4      0  144540   99.9993
6  PERF4      1       1    0.0007

--- STDT=202212 조건 추가 반영 PERF 분포 (대상: 171,751건) ---

  Column  Value   Count  Ratio(%)
0  PERF1      0  171751  100.0000
1  PERF2      0  171750   99.9994
2  PERF2      1       1    0.0006
3  PERF3      0  171751  100.0000
4  PERF4      0  171751  100.0000

### 2019년 ~ 2022년 PERF(불량률) 하락 원인 분석 및 검증 방법

앞서 확인한 결과, 씬파일러(Thin Filer) 그룹의 비율이 증가했음에도 불구하고 연체가 발생하는 불량률(PERF)은 오히려 2019년에서 2022년으로 갈수록 감소하는 추세를 보였습니다.
이에 대한 주요 원인 가설과 이를 실제 데이터로 검증할 수 있는 방법은 다음과 같습니다.

#### 1. 코로나19 관련 금융 지원 정책 효과
*   **원인 가설**: 2020년부터 시작된 코로나19 팬데믹으로 인해 정부는 소상공인 및 취약차주를 대상으로 대대적인 금융 지원(대출 만기 연장, 이자 상환 유예 등)을 시행했습니다. 이로 인해 단기적으로 연체가 발생할 가능성이 인위적으로 억제되었을 가능성이 큽니다.
*   **검증 방법**:
    *   `L10173000`(연체건수) 외에 장기/단기 연체 관련 세부 컬럼의 추이를 분석합니다.
    *   정부 지원 정책의 주요 대상이었던 특정 연령대(예: 중장년층)나 사업자 관련 플래그가 있다면, 해당 그룹의 대출 잔액 대비 연체율 변화를 비교합니다.
    *   대출 잔액 관련 컬럼(예: 총 대출금액)의 증가세와 연체 건수의 증감을 비교하여, 대출은 늘었으나 연체가 억제되었는지 확인합니다.

#### 2. 핀테크 및 간편결제 확산으로 인한 신용이력 생성 증가
*   **원인 가설**: 카카오페이, 네이버페이 등 간편결제와 인터넷전문은행의 성장으로 인해, 과거에는 금융 이력이 없던 20대(AGE_BAND=2) 등 청년층이 비교적 건전한 형태의 소액 신용/체크카드 결제 이력을 쌓게 되었습니다. 이들은 전통적인 대출 연체 위험이 적은 집단으로, 전체 씬파일러 모수(분모)를 크게 늘려 결과적으로 전체 불량률(비율)을 낮추는 착시 효과를 가져왔을 수 있습니다.
*   **검증 방법**:
    *   연도별 카드 개설 관련 컬럼(예: `C1L120004`와 유사한 신용/체크카드 보유 여부 및 건수)의 증가 추이를 확인합니다.
    *   20대 씬파일러 중 '대출 보유자'와 '카드만 보유한 자'를 분리하여 그룹별 PERF 비율을 비교합니다. 만약 카드만 보유한 그룹의 비중이 급증했고 이들의 불량률이 매우 낮다면 가설이 입증됩니다.

#### 3. 금융권의 리스크 관리 강화
*   **원인 가설**: 거시경제 불확실성이 커지면서 금융기관들이 대출 심사 기준을 강화하여, 애초에 부실 위험이 높은 취약 차주에게는 신규 대출이 나가지 않았을 수 있습니다. 즉, 신용도가 비교적 양호한 사람들만 금융거래를 시작하게 되어 전체적인 지표가 건전해졌을 수 있습니다.
*   **검증 방법**:
    *   연도별 신규 대출 개설 건수 및 금액 컬럼을 분석하여, 신용등급/점수 구간별로 신규 대출 취급 규모가 어떻게 변했는지 확인합니다.
    *   저신용자 또는 다중채무자 그룹의 비중 축소 여부를 확인합니다.

#### 향후 분석 방향
이를 정확히 확인하기 위해서는 전체 데이터셋(또는 `df_filtered`)을 바탕으로 **1) 대출 보유 여부에 따른 그룹 분리 분석**, **2) 연도별 총 대출 금액 및 신규 개설 건수의 변화 분석**을 추가로 진행해 볼 수 있습니다.

In [ ]:
import pandas as pd
from IPython.display import display

# 데이터구성상세.xlsx 파일 로드
excel_path = '/content/drive/MyDrive/데이터구성상세.xlsx'

# 엑셀 파일의 모든 시트 이름 확인
excel_file = pd.ExcelFile(excel_path)
print("시트 목록:", excel_file.sheet_names)

# 첫 번째 시트나 관련된 시트를 읽어오기 (보통 첫 번째 시트에 정리되어 있을 가능성이 높음)
df_excel = pd.read_excel(excel_path, sheet_name=0)

# 9번 폴더(개인CB)와 관련된 데이터 필터링 (컬럼명이나 내용에 '9' 또는 '개인CB' 등이 포함되어 있는지 확인)
# 데이터의 구조를 모르므로 먼저 헤더와 처음 몇 줄을 출력하여 구조 파악
display(df_excel.head(10))

시트 목록: ['1.회원 정보', '2.신용 정보', '3.승인매출 정보', '4.청구입금 정보', '5.잔액 정보', '6.채널 정보', '7.마케팅 정보', '8.성과 정보', '9.개인CB 정보', '10.기업CB 정보', '11.통신카드CB 결합정보', '12.금융상품정보', '별첨1. 개인기업CB 코드정보', '별첨2. 결합CB 코드정보']

,No,필드한글명,필드영문명,설명,코드여부,유효값,타입
0,1,기준년월,job_mon,데이터 기준년월,N,NaN,Char
1,2,발급회원번호,member_no,카드발급 회원번호,N,NaN,Char
2,3,남녀구분코드,code_gender,남녀 구분 코드,Y,1 : 남\n2 : 여,Char
3,4,연령,age,나이,N,NaN,Char
4,5,VIP등급코드,code_vip,"""01~03"" : VVIP\n""04~10"" : VIP (코드 숫자가 작을수록 높은 ...",Y,04 : VIP_4등급\n05 : VIP_3등급\n06 : VIP_2등급\n07 :...,Char
5,6,최상위카드등급코드,code_topcard_grade,소유한 카드 중 가장 등급이 높은 카드,Y,4 : 4등급\n3 : 3등급\n2 : 2등급\n1 : 1등급\n_ : 등급없음\n...,Char
6,7,회원여부_이용가능,yn_member_ups,분실/연체/한도 소진 등으로 Black List로 등재 되지 않은 회원,Y,0 : 불가\n1 : 가능,Char
7,8,회원여부_이용가능_CA,yn_ca_member_ups,분실/연체/한도 소진 등으로 Black List로 등재 되지 않아 현금서비스 \n이...,Y,0 : 불가\n1 : 가능,Char
8,9,회원여부_이용가능_카드론,yn_cl_member_ups,분실/연체/한도 소진 등으로 Black List로 등재 되지 않아 카드장기대출\n(...,Y,0 : 불가\n1 : 가능,Char
9,10,소지여부_신용,yn_credit_pss,신용카드를 소지한 회원,Y,0 : 신용카드 미소지\n1 : 신용카드 소지,Char

In [ ]:
import pandas as pd
from IPython.display import display

# '9.개인CB 정보' 시트 읽기
df_cb = pd.read_excel(excel_path, sheet_name='9.개인CB 정보')

# 전체 컬럼 목록 및 설명 확인 (주요 가설과 관련된 키워드 검색)
# 예: 대출, 카드, 연체, 신용 등의 키워드
keywords = ['대출', '카드', '연체', '신용']

# 키워드가 포함된 행 필터링
mask = df_cb['필드한글명'].str.contains('|'.join(keywords), na=False) | df_cb['설명'].str.contains('|'.join(keywords), na=False)
relevant_columns = df_cb[mask]

print(f"가설 검증 관련 주요 키워드({', '.join(keywords)})가 포함된 컬럼 목록:")
display(relevant_columns[['No', '필드한글명', '필드영문명', '설명']])

가설 검증 관련 주요 키워드(대출, 카드, 연체, 신용)가 포함된 컬럼 목록:

,No,필드한글명,필드영문명,설명
4,5,3개월내(15일)카드총이용금액(미해지),C1Z001373,기준일로부터 3개월내(15일기준) 전체카드(신용카드/신용카드+체크카드/체크카드)의 ...
5,6,3개월내(15일)신용카드일시불총이용금액(해지포함),C1M2B4W03,KCB에 등록된 카드실적정보 중 3개월내(15일기준) 신용카드 일시불 이용금액의 합계
6,7,3개월내(15일)신용카드할부총이용금액합계(해지포함),C1M2B5W03,KCB에 등록된 카드실적정보 중 3개월내(15일기준) 신용카드 할부이용금액의 총 합...
7,8,1년내(15일)카드총이용금액(미해지),C1Z001386,기준일로부터 1년내(15일기준) 전체카드(신용카드/신용카드+체크카드/체크카드)의 총...
8,9,신용카드건수(미해지),C1M210000,신용카드(신용카드/신용카드+체크카드) 개설정보의 건수
...,...,...,...,...
147,148,최근보유차량가격,AL0C00005,"KCB 수집된 차량담보정보 (C3, 실시간대출) 중 최근 보유차량 가격 (만원)"
153,154,신청일로부터 12개월 내 90일 이상 연체경험 여부,PERF1,신청일로부터 12개월 내 90일 이상 연체경험 여부
154,155,신청일로부터 12개월 내 30일 이상 연체경험 여부,PERF2,신청일로부터 12개월 내 30일 이상 연체경험 여부
155,156,신청일로부터 3개월 내 신규 대출 발생 여부,PERF3,신청일로부터 3개월 내 신규 대출 발생 여부
156,157,신청일로부터 6개월내 60일 이상 연체경험 여부,PERF4,신청일로부터 6개월내 60일 이상 연체경험 여부

In [ ]:
import pandas as pd
from IPython.display import display

# --- 1. 분석할 주요 컬럼 선정 ---
# 가설 1: 핀테크/간편결제 확산 (카드 발급 및 이용 증가)
card_cols = [c for c in ['C1M210000', 'C1Z001386', 'C1Z001373'] if c in df_filtered.columns]

# 가설 2: 리스크 관리 강화 (신용점수 상승)
score_cols = [c for c in ['SCORE_6M'] if c in df_filtered.columns]

# 가설 3: 금융 지원 효과 (대출 규모/잔액 확인)
# '대출' 및 '금액', '건수' 키워드가 들어간 주요 컬럼 자동 추출
loan_mask = df_cb['필드한글명'].str.contains('대출금액|대출건수|총대출', na=False)
loan_candidates = df_cb[loan_mask]['필드영문명'].tolist()
loan_cols = [c for c in loan_candidates if c in df_filtered.columns][:4] # 대표 4개만 추출

agg_cols = card_cols + score_cols + loan_cols

# --- 2. 연도별 지표 평균 및 비율 계산 ---
# 연도별 평균
yearly_mean = df_filtered.groupby('STDT')[agg_cols].mean().round(2)

# 가설 1을 위한 카드 실제 이용자(>0) 비율 추가
for c in card_cols:
    yearly_mean[f'{c}_이용자비율(%)'] = df_filtered.groupby('STDT')[c].apply(lambda x: (x > 0).mean() * 100).round(2)

# 컬럼 순서 정렬 (보기 편하게)
cols_order = card_cols + [f'{c}_이용자비율(%)' for c in card_cols] + score_cols + loan_cols
yearly_mean = yearly_mean[[c for c in cols_order if c in yearly_mean.columns]]

print("=== 가설 1, 2, 3 검증을 위한 연도별 주요 지표 추이 ===")
display(yearly_mean)

print("\n=== [참고] 사용된 컬럼 상세 설명 ===")
desc_df = df_cb[df_cb['필드영문명'].isin(agg_cols)][['필드영문명', '필드한글명', '설명']]
display(desc_df)

=== 가설 1, 2, 3 검증을 위한 연도별 주요 지표 추이 ===

,C1M210000,C1Z001386,C1Z001373,C1M210000_이용자비율(%),C1Z001386_이용자비율(%),C1Z001373_이용자비율(%),SCORE_6M,L10210000,L10210001,L10210002,L10210003
STDT,,,,,,,,,,,
201912,0.0,-1927.73,706.64,0.0,30.84,59.87,752.93,0.0,0.0,0.0,0.0
202012,0.0,4890.50,1103.86,0.0,59.34,63.83,755.48,0.0,0.0,0.0,0.0
202112,0.0,17849.02,3173.95,0.0,78.02,66.54,758.47,0.0,0.0,0.0,0.0
202212,0.0,13816.97,3410.28,0.0,76.28,80.73,760.15,0.0,0.0,0.0,0.0

=== [참고] 사용된 컬럼 상세 설명 ===

,필드영문명,필드한글명,설명
4,C1Z001373,3개월내(15일)카드총이용금액(미해지),기준일로부터 3개월내(15일기준) 전체카드(신용카드/신용카드+체크카드/체크카드)의 ...
7,C1Z001386,1년내(15일)카드총이용금액(미해지),기준일로부터 1년내(15일기준) 전체카드(신용카드/신용카드+체크카드/체크카드)의 총...
8,C1M210000,신용카드건수(미해지),신용카드(신용카드/신용카드+체크카드) 개설정보의 건수
48,L10210000,대출건수(미해지),KCB에 등록된 대출개설정보 중 개인대출정보의 총건수
49,L10210001,대출건수(해지포함)(1개월내신규개설),KCB에 등록된 대출개설정보 중 최근1개월내 신규로 개설된 개인대출정보의 총건수
50,L10210002,대출건수(해지포함)(2개월내신규개설),KCB에 등록된 대출개설정보 중 최근2개월내 신규로 개설된 개인대출정보의 총건수
51,L10210003,대출건수(해지포함)(3개월내신규개설),KCB에 등록된 대출개설정보 중 최근3개월내 신규로 개설된 개인대출정보의 총건수
152,SCORE_6M,신정일로부터 6개월말 시점 KCB Score,6개월전 K-Score2.0 평점

### 가설 검증 결과 요약

위 데이터 분석 결과를 바탕으로 도출된 20대(AGE_BAND=2) 씬파일러의 불량률(PERF) 하락 원인은 다음과 같습니다.

#### 1. 핀테크/간편결제 확산 (가설 1: 채택)
*   **카드 이용 금액 및 이용자 급증**: 1년 내 카드 총 이용금액(`C1Z001386`) 평균이 2019년 -1,927원에서 2022년 13,816원으로 급증했습니다.
*   **실제 이용자 비율 증가**: 카드 이용 실적이 있는 차주의 비율이 2019년 30%대에서 2021년~2022년에는 70%대 후반까지 크게 상승했습니다.
*   **해석**: 대출은 없지만 신용/체크카드를 활발히 사용하는 청년층 씬파일러가 폭발적으로 증가했다는 가설이 데이터로 명확히 입증됩니다.

#### 2. 리스크 관리 강화로 인한 신용점수 상승 (가설 2: 일부 채택)
*   전체적인 KCB 신용점수(`SCORE_6M`) 평균이 2019년 752점에서 2022년 760점으로 소폭 상승했습니다. 대출 없이 건전하게 카드만 사용하는 인원이 늘어나면서 전체적인 신용도 하방이 지지된 것으로 보입니다.

#### 3. 금융 지원 효과 및 대출 규모 (가설 3: 기각/해당 없음)
*   가장 주목할 점은 `L10210000`(대출건수)를 포함한 모든 대출 관련 지표가 2019년부터 2022년까지 **모두 0.0**으로 나타났습니다.
*   이는 우리가 설정한 필터링 조건(`D10110000=0`, `C1L120004=0`, `L10173000=0`)으로 인해 추출된 그룹이 **대출을 전혀 보유하지 않은 순수 카드 베이스 씬파일러**임을 의미합니다. 대출이 없으므로 연체가 발생할 확률도 극히 희박합니다.

#### 💡 최종 결론
2019년에서 2022년으로 갈수록 불량률(PERF)이 0%에 수렴하게 하락한 핵심 원인은 **"대출은 전혀 받지 않으면서(위험도 0), 핀테크/인터넷은행 확산으로 인해 체크/신용카드 결제 이력만 존재하는 20대 청년층이 전체 씬파일러 모수(분모)에 대거 유입되었기 때문"**입니다. 즉, 전체 파이는 커졌으나 연체 위험이 없는 집단 위주로 성장하여 전체적인 불량률 지표가 크게 개선되는 착시 및 건전화 효과가 발생했습니다.